[package]
name = "material-tester-cli"
version = "0.1.0"
edition = "2024"

[features]
ray_logging = ["tracing/ray_logging"]

[dependencies]
clap = { version = "4.6.7", default-features = false, features = ["std", "error-context", "help", "usage", "derive"] }
geometry = { version = "1.0.0", path = "../geometry" }
glam = "0.33.7"
image = { version = "0.25.10", default-features = false, features = ["png"] }
time = "0.3.55"
tracing = { version = "1.0.0", path = "../tracing" }
