[package]
name = "kdtree-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", default-features = false, features = ["derive", "std"] }
geometry = { version = "1.0.0", path = "../geometry" }
kdtree = { version = "1.0.0", path = "../kdtree" }
time = { version = "0.3.34", features = ["formatting"] }
wavefront = { version = "1.0.0", path = "../wavefront" }
