[package]
name = "pathtracer"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", default-features = false }
image = { version = "0.24.9", default-features = false, features = ["png"] }
nalgebra = "0.32.4"
nom = { version = "7.1.3", default-features = false }
rand = { version = "0.8.5", default-features = false }
rayon = "1.9.0"
rerun = { version = "0.14.1", default-features = false, features = ["run", "server"] }
