[workspace]
members = ["geometry", "kdtree", "kdtree-cli", "kdtree-reducer-cli", "kdtree-tester-cli", "pathtracer-cli", "raytracer-cli", "scene", "tracing", "wavefront"]
resolver = "2"

[profile.release]
codegen-units = 1

[profile.release-lto]
inherits = 'release'
lto = true
