[workspace]
members = ["geometry", "kdtree", "kdtree-cli", "kdtree-tester-cli", "material-tester-cli", "pathtracer-cli", "pathtracer-gui", "tracing", "wavefront", "wavefront-cli"]
resolver = "2"

[profile.release]
codegen-units = 1

[profile.release-lto]
inherits = 'release'
lto = true
