[package]
name = "pathtracer"
version = "1.0.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
clap = { version = "4.5.1", default-features = false, features = ["std", "derive"] }
image = { version = "0.24.9", default-features = false, features = ["png"] }
nalgebra = "0.32.4"
nom = { version = "7.1.3", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng", "std"] }
rayon = "1.9.0"
smallvec = "1.13.1"
termion = "3.0.0"
time = { version = "0.3.34", features = ["formatting"] }

[profile.release]
codegen-units = 1
