[package]
name = "kdtree"
version = "1.0.0"
edition = "2021"

[dependencies]
geometry = { version = "1.0.0", path = "../geometry" }
glam = "0.28.0"
rayon = { version = "1.10.0", default-features = false }
smallvec = "1.13.2"
textwrap = "0.16.1"
