[package]
name = "kdtree"
version = "1.0.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
geometry = { version = "1.0.0", path = "../geometry" }
glam = "0.29.0"
itertools = "0.13.0"
textwrap = "0.16.1"
