[package]
name = "kdtree"
version = "1.0.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
geometry = { version = "1.0.0", path = "../geometry" }
glam = "0.30.0"
itertools = "0.14.0"
textwrap = "0.16.1"
