[package]
name = "raytracer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", default-features = false, features = ["derive", "std"] }
pathtracer = { version = "1.0.0", path = ".." }
wavefront = { version = "1.0.0", path = "../wavefront" }
