name: build and test

on:
  push:
    branches: [ rust_rewrite ]
  pull_request:
    branches: [ rust_rewrite ]
  schedule:
    - cron: "0 3 1 * *"

env:
  CARGO_TERM_COLORS: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo build --verbose
    - run: cargo test --verbose
